version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    restart: always

  user-service:
    image: public.ecr.aws/x1y7v9f2/user-service:latest
    env_file:
      - .env
    restart: always

  catalog-service:
    image: public.ecr.aws/x1y7v9f2/catalog-service:latest
    env_file:
      - .env
    restart: always

  reviews-service:
    image: public.ecr.aws/x1y7v9f2/reviews-service:latest
    env_file:
      - .env
    restart: always

  likes-service:
    image: public.ecr.aws/x1y7v9f2/likes-service:latest
    env_file:
      - .env
    restart: always

  notification-service:
    image: public.ecr.aws/x1y7v9f2/notification-service:latest
    env_file:
      - .env
    depends_on:
      - rabbitmq
    restart: always

  gateway-service:
    image: public.ecr.aws/x1y7v9f2/gateway-service:latest
    ports:
      - "80:8000"
    env_file:
      - .env
    depends_on:
      - user-service
      - catalog-service
      - reviews-service
      - likes-service
    restart: always
